config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :transactions
  get 'external', to: 'transactions#external', as: 'external'  
  resources :groups   
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :transactions
  validates :name, :image, presence: true
  after_create :send_mail
  has_one_attached :image

  scope :order_scope, -> { order(name: :asc) }

  private

  def send_mail
    GroupMailer.new_group(self).deliver_now
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :group, optional: true
  validates :name, presence: true
  validates :amount, presence: true

  scope :join_scope, ->(id = params[:id]) { joins(:user).select('users.email,transactions.name,transactions.amount,transactions.created_at').where(group_id: id) }
  scope :where_destroy, ->(id = @group.id) { where(group_id: id).update_all(group_id: '') }

  scope :index_where_transaction, ->(id = current_user.id) { where(user_id: id).order(created_at: :desc).includes(:user) }
  scope :external_where_transaction, ->(id = current_user.id) { where(user_id: id, group_id: nil).order(created_at: :desc).includes(:user) }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :groups
  has_many :transactions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def validate_user
    return if user_signed_in?

    redirect_to new_user_session_path, notice: 'You must log in first'
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  include ApplicationHelper
  before_action :validate_user, except: %i[show index update edit]
  before_action :set_group, except: %i[index new create]
  # GET group
  def index
    @groups = Group.order_scope
  end

  # GET /groups/:id
  def show
    @inside_groups = Transaction.join_scope(params[:id])
  end

  # Get /groups/new
  def new
    @group = Group.new
  end

  # POST /groups/
  def create
    @group = current_user.groups.new(group_params)
    if @group.save
      redirect_to @group
    else
      render :new
    end
  end

  def edit; end

  # DELETE /groups/:id
  def destroy
    @group = Group.find(params[:id])
    Transaction.where_destroy(@group.id)
    @group.destroy
    redirect_to groups_path
  end

  # PUT /groups/:id
  def update
    if @group.update(group_params)
      redirect_to @group
    else
      render :edit
    end
  end

  private

  def set_group
    puts '**here set_group'
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  # GET /transactions
  def index
    @transactions = Transaction.index_where_transaction(current_user.id)
  end

  # GET /transactions/:id
  def show
    @transaction = Transaction.find(params[:id])
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  def edit
    @transaction = Transaction.find(params[:id])
  end

  # DELETE /transactions/:id
  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy
    redirect_to transactions_path
  end

  def update
    @transaction = Transaction.find(params[:id])
    if @transaction.update(transaction_params)
      redirect_to @transaction
    else
      render :edit
    end
  end

  def external
    # n+1
    @transactions = Transaction.external_where_transaction(current_user.id)
  end

  # POST /transactions/
  def create
    @transaction = Transaction.new(name: params[:transaction][:name],
                                   amount: params[:transaction][:amount],
                                   user_id: current_user.id,
                                   group_id: params[:transaction][:group_id])
    if @transaction.save
      redirect_to @transaction
    else
      render :new
    end
  end

  private

  def transaction_params
    params.require(:transaction).permit(:name, :amount, :group_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  include ApplicationHelper
  before_action :validate_user, except: %i[show index update edit]
end

app/helpers/application_helper.rb
module ApplicationHelper
  def transaction_image(group_id)
    if !group_id.blank?
      image_tag url_for(Group.find_by(id: group_id).image)
    else

      image_tag 'https://upload.wikimedia.org/wikipedia/commons/0/0a/No-image-available.png', class: 'w-80'
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/group/index.html.erb
<% @groups.each do |group|%>
    <h1><%= group.name%></h1>
    <div>
        <%= group.created_at%>
    </div>
<%end%>

app/views/groups/edit.html.erb
<div class= "error_message">
<%= @group.errors.full_messages.to_sentence do |message|%>    
        *<%= message %>    
<%end%>
</div>

<%= stylesheet_link_tag 'transactions', media: 'all' %>    
<div class="header">
  <div class="back">
    <%= link_to groups_path, class:'link' do %>
      <span>&#9194;</span>
    <% end %>
  </div>
  <div class="d-flex text-center flex-column pt-2 label-title">
    <h4 class="title text-uppercase text-light">Edit Group</h4>    
  </div>
  <div class="new">   
    <%= link_to 'Delete', @group,  class: "button", method: :delete%>
  </div>
</div>

<%= form_for(@group) do |f|%>    
  <div class="create-all">  
      <div class="expense_big-container d-flex align-items-center bg-light mt-3 create-items">        
        <div class="my-3 p-2 d-flex flex-column w-100">                   
            <%= f.text_field :name, palceholder: "Name"%>
        </div>
      </div>  
  </div>
  <div class="bg-success d-flex mt-2 align-items-center text-center">
    <div class="mt-4 mb-4 text-light text-casual-bold text-size mx-auto link" >
      <%= f.submit 'Save group',class:"text-uppercase  bg-success text-white" %>  
    </div>
  </div>
<%end%>

app/views/groups/index.html.erb
<%= stylesheet_link_tag 'user', media: 'all' %> 
<%= stylesheet_link_tag 'devise', media: 'all' %>
<div class="user-background d-flex flex-column justify-content-between">

  <div class="d-flex flex-column align-items-center  ">    
    <div class="text-center welcome">
      
        <h2 class="text-light welcome-title" >
        <%= link_to root_path, class:'link' do %>
          BACK
          <span>&#127968;</span>    
          HOME    
        <% end %>        
        </h2>
        <h1 class="text-light welcome-title">My groups</h1>
        <h3 class="text-light welcome-user "><%= current_user.email%></h3>      
      
    </div>
  </div>

  <% @groups.each do |group|%>
    <div class="menu-item-container">
      <div class="d-flex align-items-center ">
        <div class="user-logo-element">
          <div class="circle-logo text-light">          
            <div class="avatar">
              <%= image_tag(group.image, :class => "avatar-image")%>            
            </div> 
          </div>
        </div>
        <div class="">
          <%= link_to group.name, group, class:'link text-light text-size' %>
          <p class="group-created-delete">
            <%= group.created_at.strftime('%B %d, %Y')%> 
          </p> 
        </div>        
      </div>
    </div>
  <%end%>
    
  <div class="bg-success d-flex mt-2 align-items-center text-center">
    <%= link_to 'Create new ', new_group_path, class:"text-uppercase mt-4 mb-4 text-light text-casual-bold text-size mx-auto link" %>      
  </div>

</div>

app/views/groups/jasem.html.haml
= render_report 'my_users'

app/views/groups/new.html.erb
<div class= "error_message">
<%= @group.errors.full_messages.to_sentence do |message|%>    
        *<%= message %>    
<%end%>
</div>

<%= stylesheet_link_tag 'transactions', media: 'all' %>    

<div class="container-all-create">
  <div class="header">
    <div class="back">
      <%= link_to groups_path, class:'link' do %>
        <span>&#9194;</span>
      <% end %>
    </div>
    <div class="d-flex text-center flex-column pt-2 label-title">
      <h4 class="title text-uppercase text-light">Create Group</h4>    
    </div>
    <div class="new">   
    </div>
  </div>

  <%= form_for(@group) do |f|%>    
  <div class="create-all">  
      <div class="expense_big-container d-flex align-items-center bg-light mt-3 create-items">        
        <div class="my-3 p-2 d-flex flex-column w-100">                   
            <%= f.text_field :name, palceholder: "Name"%>
        </div>
      </div>  
      <div class="expense_big-container d-flex align-items-center bg-light mt-3 create-items">        
        <div class="my-3 p-2 d-flex flex-column w-100">                   
          <%= f.label :image %>
          <%= f.file_field :image %>
        </div>
      </div>  
      
  </div>
  <div class="bg-success d-flex align-items-center text-center save-all">
    <div class="mt-4 mb-4 text-size mx-auto ">
      <%= f.submit 'Save group',class:"text-uppercase  bg-success text-white" %>  
    </div>
  </div>
  <%end%>
</div>D

app/views/groups/show.html.erb
<%= stylesheet_link_tag 'transactions', media: 'all' %>
<%totalf=0%>            
<% @inside_groups.each do |inside|%>        
    <% totalf=totalf+inside.amount.to_int%>
<%end%>
<%totalf%>           

<div class="container-all">
  <div>
    <div class="header">
      <div class="back">
        <%= link_to groups_path, class:'link' do %>
          <span>&#9194;</span>
        <% end %>
      </div>

      <div class="label-title">
        <div class="d-flex flex-column justify-content">      
          <div class="avatar">
            <%= image_tag(@group.image, :class => "avatar-image")%>            
          </div> 
          <h4 class="title text-uppercase text-light avatar"><%= @group.name%></h4>              
          <h5 class="subtitle  "><%= @group.created_at.strftime('%B %d, %Y')%></h6>                      
          <h5 class=" subtitle ">Created by <%= @group.user.email%></h5>              
         </div> 
      </div>

      <div class="new">
        <%= link_to 'Edit', edit_group_path(@group.id), class:'button' %>
      </div>

    </div>

    <div class="total">
      <div class="total-element">
        <p class="text-size">Total</p>
      </div>

      <div class="total-element">
        <p class="text-size text-total"><%= totalf %> Hours</p>
      </div>

    </div>

    <div class="detail">
      <% @inside_groups.each do |inside| %>        
          <div class="expense_big-container d-flex align-items-center bg-light mt-3">        
            <div class="expense_big-titles p-2 d-flex flex-column w-100">
              <div class="expenses-titles d-flex justify-content-between">
                <p class="text-size pr-3"><%= inside.name %></p>
                <p class="text-size pr-3"><%= inside.amount %> Hours</p>
              </div>
              <div class="expenses-titles d-flex justify-content-between">
                <p class="text-size-small text-muted text-casual-bold pr-3"><%= inside.email %></p>
                <p class="text-size-small text-muted text-casual-bold pr-3"><%= inside.created_at.strftime('%B %d, %Y') %></p>
              </div>
            </div>
          </div>        
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VavaTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&family=Montserrat:wght@300;500;700&display=swap" rel="stylesheet">        
    <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js" integrity="sha384-SlE991lGASHoBfWbelyBPLsUlwY1GwNDJo3jSJO04KZ33K2bwfV9YBauFfnzvynJ" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>    
  </head>
  <body>    
    <% if flash[:alert].present? %>
      <p class="error_message"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/transaction/show.html.erb
<h1><%= @transaction.name %></h1>
<div>
    <%= @transaction.amount%>
</div>

app/views/transactions/edit.html.erb
<%= stylesheet_link_tag 'transactions', media: 'all' %>    
<div class= "error_message">
<%= @transaction.errors.full_messages.to_sentence do |message|%>   
        *<%= message %>            
<%end%>
</div>


<div class="container-all-create">
  <div class="header">
    <div class="back">
      <%= link_to transactions_path, class:'link' do %>
        <span>&#9194;</span>
      <% end %>
    </div>
    <div class="d-flex text-center flex-column pt-2 label-title">
      <h4 class="title text-uppercase text-light"> Edit Subject</h4>    
    </div>
    <div class="new">   
      <%= link_to 'Delete', @transaction, class: "button", remote: true, method: :delete %>
    </div>
  </div>


  <%= form_for(@transaction) do |f|%>    
    <div class="create-all">  
        <div class="expense_big-container d-flex align-items-center bg-light mt-3 create-items">        
          <div class="my-3 p-2 d-flex flex-column w-100">                   
            <%= f.collection_select :group_id, Group.all, :id, :name, include_blank: 'None', prompt: 'Select group' %>
          </div>        
        </div> 
        <div class="expense_big-container d-flex align-items-center bg-light mt-3 create-items">        
          <div class="my-3 p-2 d-flex flex-column w-100">                   
              <%= f.text_field :name, placeholder: "Name"%>
          </div>        
        </div>  
        <div class="expense_big-container d-flex align-items-center bg-light mt-3 create-items">        
          <div class="my-3 p-2 d-flex flex-column w-100">                   
            <%= f.text_field :amount, placeholder: "Amount"%>
          </div>      
        </div>  
    </div>
    <div class="bg-success d-flex mt-2 align-items-center text-center">
      <div class="mt-4 mb-4 text-light text-casual-bold text-size mx-auto link" >
        <%= f.submit 'Save subject',class:"text-uppercase  bg-success text-white" %>  
      </div>
    </div>
  <%end%>

</div>

app/views/transactions/external.html.erb
<%= stylesheet_link_tag 'transactions', media: 'all' %>
<%totalf=0%>            
<% @transactions.each do |transaction|%>        
    <% totalf=totalf+transaction.amount.to_int%>
<%end%>
<%totalf%>           

<div class="container-all">
  <div>
    <div class="header">
      <div class="back">
        <%= link_to root_path, class:'link' do %>
          <span>&#9194;</span>
        <% end %>
      </div>
      <div class="label-title">
        <h4 class="title text-uppercase text-light ">external subjects</h4>    
      </div>
      <div class="new">
        <%= link_to 'Add new', new_transaction_path, class:'button' %>
      </div>
    </div>

    <div class="total">
      <div class="total-element">
        <p class="text-size">Total</p>
      </div>
      <div class="total-element">
        <p class="text-size text-total"><%= totalf %> Hours</p>
      </div>
    </div>

    <div class="detail">
      <% @transactions.each do |transaction| %>
        <%= link_to edit_transaction_path(transaction.id), class:'link' do %>
          <div class="expense_big-container d-flex align-items-center bg-light mt-3">        
            <div class="expense_big-titles p-2 d-flex flex-column w-100">
              <div class="expenses-titles d-flex justify-content-between">
                <p class="text-size text-casual-bold pr-3"><%= transaction.name %></p>
                <p class="text-size text-casual-bold pr-3"><%= transaction.amount %> Hours</p>
              </div>
              <div class="expenses-titles d-flex justify-content-between">
                <p class="text-size-small text-muted text-casual-bold pr-3"><%= current_user.email %></p>
                <p class="text-size-small text-muted text-casual-bold pr-3"><%= transaction.created_at.strftime('%B %d, %Y') %></p>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="bg-success d-flex mt-2 align-items-center text-center">
    <%= link_to 'Add new', new_transaction_path, class:"text-uppercase mt-4 mb-4 text-light text-casual-bold text-size mx-auto link" %>
  </div>

</div>

app/views/transactions/index.html.erb
<%= stylesheet_link_tag 'transactions', media: 'all' %>
<%totalf=0%>            
<% @transactions.each do |transaction|%>        
    <% totalf=totalf+transaction.amount.to_int%>
<%end%>
<%totalf%>           

<div class="container-all">
  <div >
    <div class="header">
      <div class="back">
        <%= link_to root_path, class:'link' do %>
          <span>&#9194;</span>
        <% end %>
      </div>
      <div class="label-title">
        <h4 class="title text-uppercase text-light">My subjects</h4>    
      </div>
      <div class="new">
        <%= link_to 'Add new', new_transaction_path, class:'button ' %>
      </div>
    </div>  
    <div class="total ">
      <div class="total-element">
        <p class=" text-size">Total</p>
      </div>
      <div class="total-element">
        <p class="text-size text-total"><%= totalf %> Hours</p>
      </div>
    </div>
    <div class="detail">
      <% @transactions.each do |transaction| %>      
        <%= link_to transaction_path(transaction.id), class:'' do %>
          <div class="expense_big-container d-flex align-items-center bg-light mt-3">        
            <div class="expense_big-titles p-2 d-flex flex-column w-100">
              <div class="expenses-titles d-flex justify-content-between">
                <p class="text-size pr-3"><%= transaction.name %></p>
                <p class="text-size pr-3"><%= transaction.amount %> Hours</p>
              </div>
              <div class="expenses-titles d-flex justify-content-between">
                <p class="text-size-small text-muted pr-3"><%= current_user.email %></p>
                <p class="text-size-small text-muted pr-3"><%= transaction.created_at.strftime('%B %d, %Y') %></p>
              </div>
            </div>
            <div class="expenses-titles d-flex justify-content-between">
              <p class="text-size-small text-muted pr-3"><%= transaction_image(transaction.group_id)%> </p>                            
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="bg-success d-flex mt-2 align-items-center text-center">
    <%= link_to 'Add new', new_transaction_path, class:"text-uppercase mt-4 mb-4 text-light text-casual-bold text-size mx-auto link" %>
  </div>

</div>

app/views/transactions/new.html.erb
<div class= "error_message">
<%= @transaction.errors.full_messages.to_sentence do |message|%>   
        *<%= message %>            
<%end%>
</div>

<%= stylesheet_link_tag 'transactions', media: 'all' %>    
<div class="container-all-create">
  <div class="header">
    <div class="back">
      <%= link_to transactions_path, class:'link' do %>
        <span>&#9194;</span>
      <% end %>
    </div>
    <div class="d-flex text-center flex-column pt-2 label-title">
      <h4 class="title text-uppercase text-light"> Create Subject</h4>    
    </div>
    <div class="new">   
    </div>
  </div>
  
  <%= form_for(@transaction) do |f|%>    
  <div class="create-all">    
      <div class="expense_big-container d-flex align-items-center bg-light mt-3 create-items">        
        <div class="my-3 p-2 d-flex flex-column w-100">                   
          <%= f.collection_select :group_id, Group.all, :id, :name, include_blank: 'None', prompt: 'Select group' %>
        </div>        
      </div> 
      <div class="expense_big-container d-flex align-items-center bg-light mt-3 create-items">        
        <div class="my-3 p-2 d-flex flex-column w-100">                   
            <%= f.text_field :name, placeholder: "Name"%>
        </div>        
      </div>  
      <div class="expense_big-container d-flex align-items-center bg-light mt-3 create-items">        
        <div class="my-3 p-2 d-flex flex-column w-100 ">                   
          <%= f.text_field :amount, placeholder: "Amount"%>
        </div>      
      </div>  
  </div>  
  
  <div class="bg-success d-flex align-items-center text-center save-all">
    <div class="mt-4 mb-4 text-size mx-auto " >
      <%= f.submit 'Save subject',class:"text-uppercase  bg-success text-white" %>  
    </div>
  </div>
  
  <%end%>
  
</div>  

app/views/transactions/show.html.erb
<%= stylesheet_link_tag 'transactions', media: 'all' %>
       

<div class="container-all">
  <div>
    <div class="header">
      <div class="back">
        <%= link_to transactions_path, class:'link' do %>       
          <span>&#9194;</span>
        <% end %>
      </div>
      <div class="label-title">
        <h4 class="title text-uppercase text-light"> CREATE SUBJECT</h4>                
      </div>
      <div class="new">
        <%= link_to 'Edit', edit_transaction_path(@transaction.id), class:'button text-uppercase text-casual-bold' %>
      </div>
    </div>

    <div class="pb-5 mb-5">           
      <div class="expense_big-container d-flex align-items-center bg-light mt-3">        
        <div class="expense_big-titles p-2 d-flex flex-column w-100">
          <div class="expenses-titles d-flex justify-content-between">
            <p class="text-size text-casual-bold pr-3"><%= @transaction.name%></p>
            <p class="text-size text-casual-bold pr-3"><%= @transaction.amount %> Hours</p>
          </div>
          <div class="expenses-titles d-flex justify-content-between">            
            <p class="text-size-small text-muted text-casual-bold pr-3"><%= @transaction.created_at.strftime('%B %d, %Y') %></p>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/user/login.html.erb
<div>
  <div>
    <h4>LOGIN</h4>
  </div>
  <div >
    <%= button_to "Login", user_index_path, method: :get %>    
  </div>
</div>

<div >
    <%= text_field_tag :name, nil, placeholder: 'Name' %>
</div>

app/views/user/splash.html.erb
<div class="row center-xs">
    <div class="col-xs-6">
        <div class="box">
            snapscan
        </div>
        <div class="box">
            <%= button_to "Login", user_login_path, method: :get %>
        </div>        
    </div>
</div>

app/views/welcome/index.html.erb
<%= stylesheet_link_tag 'user', media: 'all' %>
<%= stylesheet_link_tag 'devise', media: 'all' %>
<% unless user_signed_in? %>
      <div class="container-login">
        <div class="title-vavatra">
          <h1>Snapscan</h1>                                                   
        </div>
        <div class="login-signup ">
          <div class="vavatra-login">              
            <%= link_to 'LOG IN', new_user_session_path, class:'btn-blue' %>              
            <%= link_to 'SIGN UP', new_user_registration_path,class:'btn-white'%>          
          </div>
        </div> 
      </div>        
<%else%>     
<div class="user-background d-flex flex-column justify-content-between">

  <div class="d-flex flex-column align-items-center  ">    
    <div class="text-center welcome">
      <h1 class="text-light welcome-title">Welcome</h1>
      <h3 class="text-light welcome-user "><%= current_user.email%></h3>      
    </div>
  </div>

  <div class= "menu-item-container">

    <div class="d-flex align-items-center ">
      <div class="user-logo-element">
        <div class="circle-logo text-light">
            <span class="logo-size">&#128221;</span>
        </div>
      </div>
      <div class="">
        <%= link_to 'All my subjects', transactions_path, class:'link text-light text-size' %>
      </div>
    </div>

    <div class="d-flex align-items-center  ">
      <div class="user-logo-element">
        <div class="circle-logo text-light">
            <span class="logo-size">&#128215;</span>
        </div>
      </div>
      <div class="white-line">
        <%= link_to 'All my external subjects', external_path, class:'link text-light text-size' %>        
      </div>
    </div>

    <div class=" d-flex align-items-center  ">
      <div class="user-logo-element">
        <div class="circle-logo text-light">
          <span class="logo-size">&#128218;</span>
        </div> 
      </div>
      <div class="">
        <%= link_to 'All my groups', groups_path, class:'link text-light text-size ' %>
      </div>
    </div>      
  </div>
    
  <div class="bg-success d-flex mt-2 align-items-center text-center">
    <%= link_to 'Log out', destroy_user_session_path, method: :delete, class:"text-uppercase mt-4 mb-4 text-light text-casual-bold text-size mx-auto link" %>      
  </div>
</div>
<%end%>